version: "3"

services: 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    environment: 
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.5.1
    depends_on: 
      - elasticsearch
    ports:
      - 12345:12345
      - 8080:8080
    environment: 
      - http.host="0.0.0.0"
      - xpack.monitoring.elasticsearch.hosts=["http://elasticsearch:9200"]
      - xpack.monitoring.enabled=false
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro 

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    depends_on:
      - logstash
    ports: 
      - 5601:5601
